# Generated by Django 3.2.10 on 2022-06-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfirstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessrecord',
            name='name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
